### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by aali99** [squelch0/stuf.sh#1]
Thanks for the great, useful script, 
but may you edit it to print content length too from the json file? 
it will help so much, and thanks for advance.

**Comment by squelch0** [comment]
yes, I will add that in soon. thanks for the suggestion!

**Comment by squelch0** [comment]
Alright, the content length is added! I plan on making it a parameter like '-l' soon, but for now you  can just grep or sed any output you don't like. I also plan on adding color to the output to make it easier to read. Maybe now can get some use out of ffuf's json files now! (: Gron is also a very good tool for extracting values from json files.

**Comment by squelch0** [comment]
also, if you do not want the length to be printed you can pipe it into awk: `./stuf.sh example_file.json | awk '{ print $1" "$2 }'`

**Comment by aali99** [comment]
that's great, thanks so much bro :)
